-- Generated by DDD Presenter from model "cleaning-platform". DO NOT EDIT.
-- Regenerate with `ddd generate`.
--
-- Desired PostgreSQL schema (13 or later) of the CleaningStaff context: one table per aggregate and the indexes
-- its queries need. Idempotent (IF NOT EXISTS): apply it to create a database. It does not alter existing
-- tables; derive migrations by comparing a database with this file (e.g. with a schema diff tool).

CREATE EXTENSION IF NOT EXISTS pg_trgm;

CREATE SCHEMA IF NOT EXISTS cleaning_staff;

-- Aggregate CleaningStaffInvitation. version: optimistic locking (incremented by every save).
CREATE TABLE IF NOT EXISTS cleaning_staff.cleaning_staff_invitation (
  id uuid PRIMARY KEY,
  email_value text NOT NULL,
  status text NOT NULL CHECK (status IN ('pending', 'accepted', 'revoked')),
  created_at timestamptz NOT NULL,
  expires_at timestamptz NOT NULL,
  accepted_at timestamptz,
  version bigint NOT NULL
);

-- Trigram search on email.value (search_invitations).
-- The search filters with % (served by this index), which compares with pg_trgm.similarity_threshold
-- (default 0.3): keep that setting at or below min_similarity (0.3), or rows are missed.
CREATE INDEX IF NOT EXISTS cleaning_staff_invitation_email_value_trgm_idx
  ON cleaning_staff.cleaning_staff_invitation USING gin (lower(email_value) gin_trgm_ops);

-- Keyset order of search_invitations when it does not search (a search orders by relevance first).
CREATE INDEX IF NOT EXISTS cleaning_staff_invitation_search_invitations_order_idx
  ON cleaning_staff.cleaning_staff_invitation (created_at DESC, id DESC);
