import type { ModelIR } from "@ddd/core";
import { formatSource } from "./format.ts";

/** Maximum length of a generated line (code is wrapped by `wrapLongLines`, doc comments by `docLines`). */
export const MAX_LINE = 100;

export function header(model: ModelIR): string {
  return [
    `// Generated by DDD Presenter from model "${model.project}". DO NOT EDIT.`,
    "// Regenerate with `ddd generate`; put custom code in the extensions directory.",
  ].join("\n");
}

export const SCAFFOLD_HEADER = "// Created by DDD Presenter as a starting point. This file is yours to edit.";

/**
 * A string literal as Prettier prints it: double quotes, unless the text holds more double than single quotes
 * (then single quotes, so fewer characters need escaping).
 */
export function tsString(s: string): string {
  const json = JSON.stringify(s);
  const doubles = (s.match(/"/g) ?? []).length;
  const singles = (s.match(/'/g) ?? []).length;
  if (doubles <= singles) return json;
  return `'${json.slice(1, -1).replace(/\\"/g, '"').replace(/'/g, "\\'")}'`;
}

/** `x` for `(x)` when the outer parentheses enclose the whole expression (e.g. before putting it in `if (…)`). */
export function unparen(s: string): string {
  if (!s.startsWith("(") || !s.endsWith(")")) return s;
  let depth = 0;
  let quote: string | undefined;
  for (let i = 0; i < s.length; i++) {
    const ch = s[i]!;
    if (quote) {
      if (ch === "\\") i++;
      else if (ch === quote) quote = undefined;
      continue;
    }
    if (ch === '"') quote = ch;
    else if ("([{".includes(ch)) depth++;
    else if (")]}".includes(ch)) {
      depth--;
      if (depth === 0 && i < s.length - 1) return s;
    }
  }
  return s.slice(1, -1);
}

/** Greedy word wrap; a single word longer than `width` stays on its own line. */
export function wrapWords(text: string, width: number): string[] {
  const out: string[] = [];
  let cur = "";
  for (const w of text.split(" ")) {
    if (cur && cur.length + 1 + w.length > width) {
      out.push(cur);
      cur = w;
    } else {
      cur = cur ? `${cur} ${w}` : w;
    }
  }
  out.push(cur);
  return out;
}

/**
 * A JSDoc comment as indented lines, word-wrapped to MAX_LINE. Continuation lines keep the indentation of the line
 * they continue (plus the width of a "1. " list marker), so step lists stay readable.
 */
export function docLines(text: string, pad: string, max = MAX_LINE): string[] {
  const safe = text.replace(/\*\//g, "*\\/");
  const src = safe.split("\n");
  const single = `${pad}/** ${safe} */`;
  if (src.length === 1 && single.length <= max) return [single];
  const out = [`${pad}/**`];
  for (const raw of src) {
    if (!raw.trim()) {
      out.push(`${pad} *`);
      continue;
    }
    const lead = /^ */.exec(raw)![0];
    const marker = /^\d+\. /.exec(raw.slice(lead.length))?.[0] ?? "";
    const prefix = `${pad} * ${lead}`;
    const cont = prefix + " ".repeat(marker.length);
    const first = wrapWords(raw.slice(lead.length), Math.max(20, max - prefix.length));
    const rest = first.length > 1 ? wrapWords(first.slice(1).join(" "), Math.max(20, max - cont.length)) : [];
    out.push(prefix + first[0], ...rest.map((l) => cont + l));
  }
  out.push(`${pad} */`);
  return out;
}

/** Indentation-aware line builder (two spaces per level). */
export class Code {
  private readonly lines: string[] = [];
  private depth = 0;

  line(s = ""): this {
    this.lines.push(s ? "  ".repeat(this.depth) + s : "");
    return this;
  }

  /** A line exactly as given (no indentation), e.g. the continuation of a template literal. */
  raw(s: string): this {
    this.lines.push(s);
    return this;
  }

  lines_(ss: string[]): this {
    for (const s of ss) this.line(s);
    return this;
  }

  indent(fn: () => void): this {
    this.depth++;
    fn();
    this.depth--;
    return this;
  }

  /** `head {`, the body one level deeper, then `}` (plus `tail`, e.g. `);`). */
  block(head: string, fn: () => void, tail = ""): this {
    this.line(head.endsWith("(") ? `${head}{` : `${head} {`);
    this.indent(fn);
    this.line(`}${tail}`);
    return this;
  }

  /** `head` (ending in an opening bracket), the body one level deeper, then `close`. */
  open(head: string, fn: () => void, close: string): this {
    this.line(head);
    this.indent(fn);
    this.line(close);
    return this;
  }

  doc(text: string | undefined): this {
    if (!text) return this;
    const pad = "  ".repeat(this.depth);
    for (const l of docLines(text, pad)) this.lines.push(l);
    return this;
  }

  comment(text: string): this {
    const pad = "  ".repeat(this.depth);
    for (const l of wrapWords(text, MAX_LINE - pad.length - 3)) this.lines.push(`${pad}// ${l}`);
    return this;
  }

  toString(): string {
    return this.lines.join("\n");
  }
}

// ---------------------------------------------------------------------------
// Imports
// ---------------------------------------------------------------------------

/**
 * Collects imports of one file. Modules are external package names (`zod`) or project-relative module paths without
 * extension (`src/pkg/generated/runtime`), rendered as relative `.js` specifiers (ESM / NodeNext). Names used only
 * as types are imported with `import type` (verbatimModuleSyntax).
 */
export class TsImports {
  private readonly values = new Map<string, Set<string>>();
  private readonly types = new Map<string, Set<string>>();
  private readonly namespaces = new Map<string, string>();

  /** `self`: module path of the file being written (imports from itself are dropped). */
  constructor(private readonly self: string) {}

  value(module: string, ...names: string[]): this {
    if (module === this.self) return this;
    const set = this.values.get(module) ?? new Set<string>();
    for (const n of names) set.add(n);
    this.values.set(module, set);
    return this;
  }

  type(module: string, ...names: string[]): this {
    if (module === this.self) return this;
    const set = this.types.get(module) ?? new Set<string>();
    for (const n of names) set.add(n);
    this.types.set(module, set);
    return this;
  }

  namespace(module: string, alias: string): this {
    this.namespaces.set(module, alias);
    return this;
  }

  render(): string {
    const modules = [...new Set([...this.values.keys(), ...this.types.keys(), ...this.namespaces.keys()])];
    const spec = (m: string) => (isExternal(m) ? m : relativeSpecifier(this.self, m));
    const external = modules.filter(isExternal).sort();
    const local = modules.filter((m) => !isExternal(m)).sort((a, b) => spec(a).localeCompare(spec(b)));
    const lines: string[] = [];
    for (const group of [external, local]) {
      for (const m of group) {
        const ns = this.namespaces.get(m);
        if (ns) lines.push(`import * as ${ns} from "${spec(m)}";`);
        const values = this.values.get(m) ?? new Set<string>();
        const types = [...(this.types.get(m) ?? [])].filter((t) => !values.has(t));
        if (!values.size && !types.length) continue;
        const names = [...[...values].map((v) => ({ n: v, t: false })), ...types.map((t) => ({ n: t, t: true }))].sort((a, b) => a.n.localeCompare(b.n));
        if (!values.size) lines.push(`import type { ${names.map((x) => x.n).join(", ")} } from "${spec(m)}";`);
        else lines.push(`import { ${names.map((x) => (x.t ? `type ${x.n}` : x.n)).join(", ")} } from "${spec(m)}";`);
      }
      if (group === external && external.length && local.length) lines.push("");
    }
    return lines.join("\n");
  }
}

/** Packages the generated code imports; every other module is a project-relative path. */
const EXTERNAL = new Set(["zod", "decimal.js", "vitest", "bun:test", "node:crypto", "@tanstack/react-query", "react", "jose"]);

function isExternal(m: string): boolean {
  return EXTERNAL.has(m);
}

/** `./x.js` / `../a/b.js` from the module `from` to the module `to` (both project-relative, no extension). */
export function relativeSpecifier(from: string, to: string): string {
  const a = from.split("/").slice(0, -1);
  const b = to.split("/");
  let i = 0;
  while (i < a.length && i < b.length - 1 && a[i] === b[i]) i++;
  const up = a.length - i;
  const rest = b.slice(i).join("/");
  return `${up === 0 ? "./" : "../".repeat(up)}${rest}.js`;
}

/** File header, imports and body; over-long lines are re-printed with Prettier's rules (format.ts). */
export function assemble(head: string, doc: string | undefined, imports: TsImports, body: string): string {
  const parts = [head];
  if (doc) parts.push(docLines(doc, "").join("\n"));
  const imp = imports.render();
  if (imp) parts.push(imp);
  return formatSource(parts.join("\n\n") + "\n\n" + body.trim() + "\n");
}
