import { ruleUsage, type Analysis } from "@ddd/core";
import type { PyFile } from "./domain.ts";
import type { Layout } from "./layout.ts";
import { pascal } from "./support.ts";

const esc = (s: string) => s.replace(/\|/g, "\\|").replace(/\n/g, " ");

/** Human-readable reference of the context: rules, where they apply, use case steps and scenarios. */
export function contextReadme(L: Layout, analysis: Analysis): PyFile {
  const ctx = L.ca.ir;
  const out: string[] = [];
  out.push(`<!-- Generated by DDD Presenter from model "${L.model.project}". DO NOT EDIT. -->`, "");
  out.push(`# ${ctx.name}`, "");
  if (ctx.description) out.push(ctx.description, "");
  if (ctx.glossary.length) {
    out.push("## Glossary", "", "| Term | Definition |", "|---|---|");
    for (const g of ctx.glossary) out.push(`| ${esc(g.term)} | ${esc(g.definition)} |`);
    out.push("");
  }
  const usage = ruleUsage(analysis).filter((u) => u.context === ctx.name);
  if (usage.length) {
    out.push("## Rules", "", "| Rule | Kind | Owner | Condition | Error | Applied by | Tested by |", "|---|---|---|---|---|---|---|");
    for (const u of usage) {
      const applied = u.appliedBy.map((a) => `${a.kind} \`${a.name}\``).join(", ") || "—";
      const tests = u.tests.map((t) => `\`${t}\``).join(", ") || "—";
      out.push(`| \`${u.rule}\` | ${u.kind === "invariant" ? "Invariant" : "StateGuard"} | ${u.owner} | \`${esc(u.expression)}\` | ${u.error} | ${applied} | ${tests} |`);
    }
    out.push("");
    const untested = usage.filter((u) => u.tests.length === 0);
    if (untested.length) out.push(`> Rules without a scenario that exercises their error: ${untested.map((u) => `\`${u.rule}\``).join(", ")}`, "");
  }
  for (const ag of ctx.aggregates) {
    out.push(`## Aggregate ${ag.name}`, "");
    if (ag.description) out.push(ag.description, "");
    out.push("| Operation | Requires (auto) | Changes | Emits |", "|---|---|---|---|");
    for (const f of ag.factories) out.push(`| \`${f.name}\` (factory) | — | all fields | ${f.emits.map((e) => e.name).join(", ") || "—"} |`);
    for (const op of ag.operations) {
      out.push(`| \`${op.name}\` | ${op.require.map((r) => `\`${r}\``).join(", ") || "—"} | ${Object.keys(op.changes).join(", ") || "—"} | ${op.emits.map((e) => e.name).join(", ") || "—"} |`);
    }
    out.push("");
  }
  for (const uc of ctx.useCases) {
    out.push(`## Use case ${uc.name}`, "");
    if (uc.description) out.push(uc.description, "");
    out.push(`- Class: \`${pascal(uc.name)}UseCase\`, command: \`${uc.command}\``);
    if (uc.actor) out.push(`- Actor: ${uc.actor}`);
    out.push(`- Transaction: ${uc.transaction}`);
    out.push(`- Scenarios: ${uc.scenarios.map((s) => `\`${s.name}\``).join(", ") || "none"}`, "");
  }
  return { path: `${L.model.generation.srcDir}/${L.base.replace(/\./g, "/")}/README.md`, content: out.join("\n").trimEnd() + "\n" };
}
