import { ruleUsage, type Analysis } from "@ddd/core";
import type { PyFile } from "./domain.ts";
import type { Layout } from "./layout.ts";
import { policyClass } from "./policies.ts";
import { pascal } from "./support.ts";

const esc = (s: string) => s.replace(/\|/g, "\\|").replace(/\n/g, " ");

/** Human-readable reference of the context: rules, where they apply, use case steps and scenarios. */
export function contextReadme(L: Layout, analysis: Analysis): PyFile {
  const ctx = L.ca.ir;
  const out: string[] = [];
  out.push(`<!-- Generated by DDD Presenter from model "${L.model.project}". DO NOT EDIT. -->`, "");
  out.push(`# ${ctx.name}`, "");
  if (ctx.description) out.push(ctx.description, "");
  if (ctx.subdomain) out.push(`Subdomain: **${ctx.subdomain}**`, "");
  if (ctx.glossary.length) {
    out.push("## Glossary", "", "| Term | Definition |", "|---|---|");
    for (const g of ctx.glossary) out.push(`| ${esc(g.term)} | ${esc(g.definition)} |`);
    out.push("");
  }
  const usage = ruleUsage(analysis).filter((u) => u.context === ctx.name);
  if (usage.length) {
    out.push("## Rules", "", "| Rule | Kind | Owner | Condition | Error | Applied by | Tested by |", "|---|---|---|---|---|---|---|");
    for (const u of usage) {
      const applied = u.appliedBy.map((a) => `${a.kind} \`${a.name}\``).join(", ") || "—";
      const tests = u.tests.map((t) => `\`${t}\``).join(", ") || "—";
      out.push(`| \`${u.rule}\` | ${u.kind === "invariant" ? "Invariant" : "StateGuard"} | ${u.owner} | \`${esc(u.expression)}\` | ${u.error} | ${applied} | ${tests} |`);
    }
    out.push("");
    const untested = usage.filter((u) => u.tests.length === 0);
    if (untested.length) out.push(`> Rules without a scenario that exercises their error: ${untested.map((u) => `\`${u.rule}\``).join(", ")}`, "");
  }
  for (const ag of ctx.aggregates) {
    out.push(`## Aggregate ${ag.name}`, "");
    if (ag.description) out.push(ag.description, "");
    out.push("| Operation | Requires (auto) | Changes | Emits |", "|---|---|---|---|");
    for (const f of ag.factories) out.push(`| \`${f.name}\` (factory) | — | all fields | ${f.emits.map((e) => e.name).join(", ") || "—"} |`);
    for (const op of ag.operations) {
      out.push(`| \`${op.name}\` | ${op.require.map((r) => `\`${r}\``).join(", ") || "—"} | ${Object.keys(op.changes).join(", ") || "—"} | ${op.emits.map((e) => e.name).join(", ") || "—"} |`);
    }
    out.push("");
  }
  for (const uc of ctx.useCases) {
    out.push(`## Use case ${uc.name}`, "");
    if (uc.description) out.push(uc.description, "");
    out.push(`- Class: \`${pascal(uc.name)}UseCase\`, command: \`${uc.command}\``);
    if (uc.actor) out.push(`- Actor: ${uc.actor}`);
    out.push(`- Transaction: ${uc.transaction}`);
    out.push(`- Scenarios: ${uc.scenarios.map((s) => `\`${s.name}\``).join(", ") || "none"}`, "");
  }
  if (ctx.policies.length) {
    out.push("## Policies", "", "| Policy | When | Runs | Args |", "|---|---|---|---|");
    for (const p of ctx.policies) {
      const info = L.ca.policies.get(p.name);
      const when = info ? (info.crossContext ? `${info.event.context}.${info.event.name}` : info.event.name) : p.when;
      const args = Object.entries(p.args).map(([k, v]) => `${k}=\`${esc(v)}\``).join(", ") || "—";
      out.push(`| \`${p.name}\` (\`${policyClass(p)}\`)${p.description ? ` — ${esc(p.description)}` : ""} | ${when} | \`${p.run}\` | ${args} |`);
    }
    out.push("", "Wire the handlers into an event bus with `subscriptions()` in `application/policies.py`.", "");
  }
  const rels = L.model.relationships.filter((r) => r.upstream === ctx.name || r.downstream === ctx.name);
  if (rels.length) {
    out.push("## Context map", "", "```mermaid", "flowchart LR");
    for (const r of rels) {
      const label = [r.pattern, r.events.join(", ")].filter(Boolean).join(": ");
      out.push(`  ${r.upstream} -->|"${label.replace(/"/g, "'")}"| ${r.downstream}`);
    }
    out.push("```", "", "| Upstream | Downstream | Pattern | Events | Consumed by |", "|---|---|---|---|---|");
    for (const r of rels) {
      const down = analysis.contexts.get(r.downstream);
      const consumers = down ? [...down.policies.entries()].filter(([, i]) => i.event.context === r.upstream && r.events.includes(i.event.name)).map(([n]) => `${r.downstream}.${n}`) : [];
      out.push(`| ${r.upstream} | ${r.downstream} | ${r.pattern} | ${r.events.join(", ") || "—"} | ${consumers.map((x) => `\`${x}\``).join(", ") || "—"} |`);
    }
    out.push("");
  }
  return { path: `${L.model.generation.srcDir}/${L.base.replace(/\./g, "/")}/README.md`, content: out.join("\n").trimEnd() + "\n" };
}
