import type { ContextAnalysis, ModelIR, Type } from "@ddd/core";
import { Imports, toSnake, type ExprContext } from "./support.ts";

/** Module / path layout for one bounded context. */
export class Layout {
  readonly pkg: string;
  readonly ctxModule: string;
  readonly base: string;

  constructor(
    readonly model: ModelIR,
    readonly ca: ContextAnalysis,
  ) {
    this.pkg = model.generation.package;
    this.ctxModule = toSnake(ca.ir.name);
    this.base = `${this.pkg}.generated.${this.ctxModule}`;
  }

  get runtime(): string {
    return `${this.pkg}.generated._runtime`;
  }
  mod(name: "enums" | "value_objects" | "entities" | "aggregates" | "events" | "errors" | "commands" | "rules"): string {
    return `${this.base}.domain.${name}`;
  }
  get ports(): string {
    return `${this.base}.application.ports`;
  }
  get useCases(): string {
    return `${this.base}.application.use_cases`;
  }
  get testing(): string {
    return `${this.base}.testing`;
  }

  typeModule = (kind: "enum" | "vo" | "entity" | "aggregate" | "event", _name: string): string => {
    switch (kind) {
      case "enum":
        return this.mod("enums");
      case "vo":
        return this.mod("value_objects");
      case "entity":
        return this.mod("entities");
      case "aggregate":
        return this.mod("aggregates");
      case "event":
        return this.mod("events");
    }
  };

  /** Source path of a module, relative to the project root. */
  path(module: string): string {
    return `${this.model.generation.srcDir}/${module.replace(/\./g, "/")}.py`;
  }

  testPath(name: string): string {
    return `${this.model.generation.testsDir}/generated/test_${this.ctxModule}_${name}.py`;
  }

  fieldTypes(owner: string): Map<string, Type> {
    return this.ca.fieldTypes.get(owner) ?? new Map();
  }

  exprCtx(imports: Imports, self: string, extra: Partial<ExprContext> = {}): ExprContext {
    return { self, imports, typeModule: this.typeModule, ...extra };
  }
}

/** Imports that silently drop names from the module being written. */
export class ModuleImports extends Imports {
  constructor(private readonly self: string) {
    super();
    this.from("__future__", "annotations");
  }
  override from(module: string, ...names: string[]): this {
    if (module === this.self) return this;
    return super.from(module, ...names);
  }
}

export function header(model: ModelIR, extra?: string): string {
  const lines = [
    `# Generated by DDD Presenter from model "${model.project}". DO NOT EDIT.`,
    "# Regenerate with `ddd generate`; put custom code in the extensions package.",
  ];
  if (extra) lines.push(`# ${extra}`);
  return lines.join("\n");
}

export function assemble(model: ModelIR, doc: string | undefined, imports: Imports, body: string): string {
  const head = [header(model)];
  if (doc) head.push(`"""${doc}"""`);
  const imp = imports.render();
  if (imp) head.push(imp);
  const text = head.join("\n\n") + "\n\n\n" + body.trim() + "\n";
  return wrapLongLines(text);
}

const MAX_LINE = 100;

/** Splits over-long single-line calls/signatures into one argument per line (outside docstrings/comments). */
export function wrapLongLines(src: string, max = MAX_LINE): string {
  const out: string[] = [];
  let inDoc = false;
  for (const line of src.split("\n")) {
    const quotes = (line.match(/"""/g) ?? []).length;
    const wasInDoc = inDoc;
    if (quotes % 2 === 1) inDoc = !inDoc;
    if (wasInDoc || quotes > 0 || line.length <= max || line.trimStart().startsWith("#")) {
      out.push(line);
      continue;
    }
    out.push(...wrapLine(line, max));
  }
  return out.join("\n");
}

function wrapLine(line: string, max: number): string[] {
  const indent = /^ */.exec(line)![0];
  // Find the outermost parenthesized group that ends last on the line.
  let depth = 0;
  let open = -1;
  let close = -1;
  let quote: string | undefined;
  for (let i = 0; i < line.length; i++) {
    const ch = line[i]!;
    if (quote) {
      if (ch === "\\") i++;
      else if (ch === quote) quote = undefined;
      continue;
    }
    if (ch === '"' || ch === "'") quote = ch;
    else if (ch === "(" || ch === "[" || ch === "{") {
      if (depth === 0 && ch === "(" && open === -1) open = i;
      depth++;
    } else if (ch === ")" || ch === "]" || ch === "}") {
      depth--;
      if (depth === 0 && ch === ")" && open !== -1 && close === -1) close = i;
    }
  }
  if (open === -1 || close === -1) return [line];
  const inner = line.slice(open + 1, close);
  const args = splitTopLevel(inner);
  if (args.length < 2 && inner.length < max) return [line];
  const head = line.slice(0, open + 1);
  const tail = line.slice(close);
  const body = args.map((a) => `${indent}    ${a.trim()},`);
  const lines = [head, ...body, `${indent}${tail}`];
  return lines.flatMap((l, i) => (i > 0 && i < lines.length - 1 && l.length > max ? wrapLine(l.replace(/,$/, ""), max).map((x, j, arr) => (j === arr.length - 1 ? `${x},` : x)) : [l]));
}

function splitTopLevel(s: string): string[] {
  const out: string[] = [];
  let depth = 0;
  let quote: string | undefined;
  let start = 0;
  for (let i = 0; i < s.length; i++) {
    const ch = s[i]!;
    if (quote) {
      if (ch === "\\") i++;
      else if (ch === quote) quote = undefined;
      continue;
    }
    if (ch === '"' || ch === "'") quote = ch;
    else if ("([{".includes(ch)) depth++;
    else if (")]}".includes(ch)) depth--;
    else if (ch === "," && depth === 0) {
      out.push(s.slice(start, i));
      start = i + 1;
    }
  }
  const last = s.slice(start);
  if (last.trim()) out.push(last);
  return out;
}
