import type { ContextAnalysis, ModelIR, Type } from "@ddd/core";
import { byDunderAll, docstringLines, Imports, MAX_LINE, toSnake, wrapWords, type ExprContext } from "./support.ts";

/** Module / path layout for one bounded context. */
export class Layout {
  readonly pkg: string;
  readonly ctxModule: string;
  readonly base: string;

  constructor(
    readonly model: ModelIR,
    readonly ca: ContextAnalysis,
  ) {
    this.pkg = model.generation.package;
    this.ctxModule = toSnake(ca.ir.name);
    this.base = `${this.pkg}.generated.${this.ctxModule}`;
  }

  get runtime(): string {
    return `${this.pkg}.generated._runtime`;
  }
  mod(name: "enums" | "value_objects" | "entities" | "aggregates" | "events" | "errors" | "commands" | "rules"): string {
    return `${this.base}.domain.${name}`;
  }
  get ports(): string {
    return `${this.base}.application.ports`;
  }
  get useCases(): string {
    return `${this.base}.application.use_cases`;
  }
  get policies(): string {
    return `${this.base}.application.policies`;
  }
  /** Events module of any context of the model (upstream events are imported from here). */
  eventsOf(context: string): string {
    return `${this.pkg}.generated.${toSnake(context)}.domain.events`;
  }
  get testing(): string {
    return `${this.base}.testing`;
  }

  typeModule = (kind: "enum" | "vo" | "entity" | "aggregate" | "event", _name: string): string => {
    switch (kind) {
      case "enum":
        return this.mod("enums");
      case "vo":
        return this.mod("value_objects");
      case "entity":
        return this.mod("entities");
      case "aggregate":
        return this.mod("aggregates");
      case "event":
        return this.mod("events");
    }
  };

  /** Source path of a module, relative to the project root. */
  path(module: string): string {
    return `${this.model.generation.srcDir}/${module.replace(/\./g, "/")}.py`;
  }

  testPath(name: string): string {
    return `${this.model.generation.testsDir}/generated/test_${this.ctxModule}_${name}.py`;
  }

  fieldTypes(owner: string): Map<string, Type> {
    return this.ca.fieldTypes.get(owner) ?? new Map();
  }

  exprCtx(imports: Imports, self: string, extra: Partial<ExprContext> = {}): ExprContext {
    return { self, imports, typeModule: this.typeModule, ...extra };
  }
}

/** Imports that silently drop names from the module being written. */
export class ModuleImports extends Imports {
  constructor(private readonly self: string) {
    super();
    this.from("__future__", "annotations");
  }
  override from(module: string, ...names: string[]): this {
    if (module === this.self) return this;
    return super.from(module, ...names);
  }
}

export function header(model: ModelIR, extra?: string): string {
  const lines = [
    `# Generated by DDD Presenter from model "${model.project}". DO NOT EDIT.`,
    "# Regenerate with `ddd generate`; put custom code in the extensions package.",
  ];
  if (extra) lines.push(`# ${extra}`);
  return lines.join("\n");
}

export interface AssembleOptions {
  /** Declare the module's public names in `__all__` (default true; off for test modules and scaffolds). */
  exports?: boolean;
}

export function assemble(model: ModelIR, doc: string | undefined, imports: Imports, body: string, opts: AssembleOptions = {}): string {
  const head = [header(model)];
  if (doc) head.push(docstringLines(doc, "").join("\n"));
  const imp = imports.render();
  if (imp) head.push(imp);
  const code = body.trim();
  const exported = opts.exports === false ? [] : publicNames(code);
  if (exported.length) head.push(dunderAll(exported));
  // Like ruff (isort + format): two blank lines before a class or function, one before anything else.
  const gap = /^(class |def |@)/.test(code) ? "\n\n\n" : "\n\n";
  const text = head.join("\n\n") + gap + code + "\n";
  return wrapLongLines(text);
}

/** Top-level classes, functions and assignments of a module body that do not start with an underscore. */
export function publicNames(body: string): string[] {
  const names = new Set<string>();
  for (const line of body.split("\n")) {
    const m = /^(?:class |def )?([A-Za-z]\w*)\s*(?:[(:]|=(?!=))/.exec(line);
    if (m && !/^(?:if|for|while|with|try|except|else|elif|return|raise|assert|import|from)$/.test(m[1]!)) names.add(m[1]!);
  }
  return [...names].sort(byDunderAll);
}

function dunderAll(names: string[]): string {
  const one = `__all__ = [${names.map((n) => `"${n}"`).join(", ")}]`;
  if (one.length <= MAX_LINE) return one;
  return `__all__ = [\n${names.map((n) => `    "${n}",`).join("\n")}\n]`;
}

// ---------------------------------------------------------------------------
// Line wrapping
//
// Generated code stays within MAX_LINE characters. Over-long lines are split only inside brackets, where Python
// allows line breaks without changing meaning. The one thing that must never happen is turning a grouping
// parenthesis into a tuple: `if not (a or b,):` is always true. So a trailing comma is added only to groups that
// already hold several comma-separated elements (argument lists, tuple/list literals) or that already end with one.
// ---------------------------------------------------------------------------

/** Splits over-long lines (outside docstrings) at bracket boundaries; long comments become several comment lines. */
export function wrapLongLines(src: string, max = MAX_LINE): string {
  const out: string[] = [];
  let inDoc = false;
  for (const line of src.split("\n")) {
    const quotes = (line.match(/"""/g) ?? []).length;
    const wasInDoc = inDoc;
    if (quotes % 2 === 1) inDoc = !inDoc;
    if (wasInDoc || quotes > 0 || line.length <= max) {
      out.push(line);
      continue;
    }
    if (line.trimStart().startsWith("#")) {
      out.push(...wrapComment(line, max));
      continue;
    }
    out.push(...wrapLine(line, max));
  }
  return out.join("\n");
}

function wrapComment(line: string, max: number): string[] {
  const indent = /^ */.exec(line)![0];
  const text = line.trimStart().replace(/^#\s?/, "");
  return wrapWords(text, max - indent.length - 2).map((l) => `${indent}# ${l}`);
}

interface Group {
  open: number;
  close: number;
}

/** Bracket groups at nesting depth 0 (string literals are skipped). */
function topGroups(line: string): Group[] {
  const groups: Group[] = [];
  let depth = 0;
  let open = -1;
  let quote: string | undefined;
  for (let i = 0; i < line.length; i++) {
    const ch = line[i]!;
    if (quote) {
      if (ch === "\\") i++;
      else if (ch === quote) quote = undefined;
      continue;
    }
    if (ch === '"' || ch === "'") quote = ch;
    else if ("([{".includes(ch)) {
      if (depth === 0) open = i;
      depth++;
    } else if (")]}".includes(ch)) {
      depth--;
      if (depth === 0 && open !== -1) groups.push({ open, close: i });
    }
  }
  return groups;
}

/** Offsets of `needle` (e.g. "," or " or ") at nesting depth 0, outside string literals. */
function topLevel(s: string, needle: string): number[] {
  const out: number[] = [];
  let depth = 0;
  let quote: string | undefined;
  for (let i = 0; i < s.length; i++) {
    const ch = s[i]!;
    if (quote) {
      if (ch === "\\") i++;
      else if (ch === quote) quote = undefined;
      continue;
    }
    if (ch === '"' || ch === "'") quote = ch;
    else if ("([{".includes(ch)) depth++;
    else if (")]}".includes(ch)) depth--;
    else if (depth === 0 && s.startsWith(needle, i)) out.push(i);
  }
  return out;
}

// The rules below follow ruff format (Black style), so that `ruff format --check` accepts the generated code:
// - an expression is split before the operators of its loosest-binding level, the operator leading the line; an
//   operand that still does not fit is split the same way at the same indentation, then at its brackets;
// - at statement level (`if`, `return`, `x = ...`) the value is put in parentheses unless it has a single such
//   operator and its first operand starts (or its last operand ends) with a bracket: then that bracket is split;
// - of several bracket groups on a line, the first one that does not fit up to the next group is split;
// - a comprehension is split before its `for` / `if` clauses.

/** Operator levels from the loosest binding to the tightest (a split happens before each operator of one level). */
const LEVELS: string[][] = [
  [" if ", " else "],
  [" or "],
  [" and "],
  [" not in ", " is not ", " == ", " != ", " <= ", " >= ", " < ", " > ", " in ", " is "],
  [" | "],
  [" + ", " - "],
  [" * ", " // ", " / ", " % "],
];

interface Op {
  at: number;
  op: string;
}

/** Top-level operators of one level, in order (a longer operator hides the shorter ones it contains). */
function operatorsAt(expr: string, level: string[]): Op[] {
  const found: Op[] = [];
  for (const op of [...level].sort((a, b) => b.length - a.length)) {
    for (const at of topLevel(expr, op)) {
      if (!found.some((f) => at < f.at + f.op.length && f.at < at + op.length)) found.push({ at, op });
    }
  }
  return found.sort((a, b) => a.at - b.at);
}

/** The operators of the loosest level present at the top level of `expr`. */
function loosest(expr: string): Op[] {
  if (topLevel(expr, "lambda").length) return [];
  for (const level of LEVELS) {
    const ops = operatorsAt(expr, level);
    if (ops.length) return ops;
  }
  return [];
}

/** Splits before each operator; every part after the first starts with its operator. */
function splitAt(expr: string, ops: Op[]): string[] {
  const parts: string[] = [];
  let start = 0;
  for (const { at } of ops) {
    parts.push(expr.slice(start, at).trim());
    start = at + 1;
  }
  parts.push(expr.slice(start).trim());
  return parts;
}

/** The element and the `for` / `if` clauses of a comprehension, or undefined. */
function comprehensionParts(expr: string): string[] | undefined {
  const fors = topLevel(expr, " for ");
  if (!fors.length) return undefined;
  const cuts = [...fors, ...topLevel(expr, " if ").filter((i) => i > fors[0]!)].sort((a, b) => a - b);
  return splitAt(expr, cuts.map((at) => ({ at, op: "" })));
}

/** ruff: optional parentheses are left out when the only split operator has a bracketed first or last operand. */
function canOmitParens(value: string, ops: Op[]): boolean {
  if (ops.length !== 1) return false;
  const [first, second] = splitAt(value, ops) as [string, string];
  const last = second.slice(ops[0]!.op.trim().length).trim();
  const empty = /^(\(\)|\[\]|\{\})$/;
  const opens = /^[([{]/.test(first) && !empty.test(first.slice(0, 2));
  const closes = /[)\]}]$/.test(last) && !empty.test(last.slice(-2));
  return opens || closes;
}

const OPERATOR_LEAD = /^(?:not in |is not |for |if |else |or |and |== |!= |<= |>= |< |> |in |is |\| |\+ |- |\* |\/\/ |\/ |% )/;

/** One operand of a split expression (possibly led by its operator): split tighter operators, then brackets. */
function wrapPiece(line: string, max: number): string[] {
  if (line.length <= max) return [line];
  const indent = /^ */.exec(line)![0];
  const text = line.slice(indent.length);
  const lead = OPERATOR_LEAD.exec(text)?.[0] ?? "";
  const rest = text.slice(lead.length);
  const ops = lead === "for " ? [] : loosest(rest);
  if (ops.length) {
    const parts = splitAt(rest, ops);
    parts[0] = lead + parts[0];
    return parts.flatMap((p) => wrapPiece(indent + p, max));
  }
  return wrapLine(line, max, lead === "");
}

/** `if …:`, `return …`, `assert …`, `x = …`, `x: T = …` and `name=…,` lines. */
const STATEMENT = /^(if |elif |while |return |assert |[A-Za-z_][\w.]*(?:: [^=]*?)? = |[A-Za-z_]\w*=(?!=))(.*?)(:|,)?$/;

function wrapLine(line: string, max: number, statement = true): string[] {
  if (line.length <= max) return [line];
  const indent = /^ */.exec(line)![0];
  const inner = indent + "    ";

  // A trailing comment must not end up inside the brackets: move it to its own line above the code.
  const hash = topLevel(line, "#").find((i) => i > indent.length && /\s/.test(line[i - 1]!));
  if (hash !== undefined) {
    return [...wrapComment(`${indent}${line.slice(hash)}`, max), ...wrapLine(line.slice(0, hash).trimEnd(), max, statement)];
  }

  // A value with operators outside any bracket: put it in parentheses, one operand per line (a keyword argument
  // always gets them; ruff keeps explicit parentheses there).
  const m = statement ? STATEMENT.exec(line.slice(indent.length)) : null;
  let valueStart = 0;
  if (m) {
    const lead = m[1]!;
    const value = m[2]!;
    const end = m[3] ?? "";
    const ops = topLevel(value, ",").length ? [] : loosest(value);
    if (ops.length && (/^[A-Za-z_]\w*=$/.test(lead) || !canOmitParens(value, ops))) {
      return [`${indent}${lead}(`, ...splitAt(value, ops).flatMap((p) => wrapPiece(inner + p, max)), `${indent})${end}`];
    }
    if (lead.endsWith(" = ")) {
      // An assignment splits its value, never its target or annotation; a value without a closing bracket
      // (a name, an attribute, a string) goes into parentheses.
      valueStart = indent.length + lead.length;
      if (!ops.length && !/[)\]}]$/.test(value) && (inner + value).length <= max) {
        return [`${indent}${lead}(`, inner + value, `${indent})${end}`];
      }
    }
  }

  // Otherwise split the first bracket group that does not fit up to the next group (or the end of the line).
  const groups = topGroups(line).filter((g) => g.open >= valueStart && line.slice(g.open + 1, g.close).trim());
  if (!groups.length) return splitString(line, max);
  let g = groups[groups.length - 1]!;
  // A function signature splits its parameters, never its return annotation.
  if (/^(async )?def /.test(line.slice(indent.length))) g = groups[0]!;
  else for (let i = 0; i < groups.length; i++) {
    const until = i + 1 < groups.length ? groups[i + 1]!.open + 1 : line.length;
    if (until > max) {
      g = groups[i]!;
      break;
    }
  }
  const content = line.slice(g.open + 1, g.close);
  const head = line.slice(0, g.open + 1);
  const tail = `${indent}${line.slice(g.close)}`;
  const elements = splitTopLevel(content);
  if (elements.length < 2 && !content.trimEnd().endsWith(",")) {
    // One element: a grouping parenthesis, a single argument or a bare generator expression. Never add a comma.
    const one = content.trim();
    if ((inner + one).length <= max) return [head, inner + one, tail];
    const comprehension = comprehensionParts(one);
    const parts = comprehension ?? splitAt(one, loosest(one));
    return [head, ...parts.flatMap((p) => wrapPiece(inner + p, max)), tail];
  }
  const body = elements.flatMap((el) => {
    const text = el.trim();
    const own = `${inner}${text}`;
    // The element line gets a trailing comma, which must fit too.
    const fits = own.length + 1 <= max;
    const ops = /^[A-Za-z_]\w*=(?!=)|^\*/.test(text) ? [] : loosest(text);
    const parts = fits
      ? [own]
      : ops.length
        ? // An operator chain as a positional element: parenthesize it, one operand per line.
          [`${inner}(`, ...splitAt(text, ops).flatMap((p) => wrapPiece(`${inner}    ${p}`, max)), `${inner})`]
        : wrapLine(own, own.length === max ? max - 1 : max);
    parts[parts.length - 1] += ",";
    return parts;
  });
  return [head, ...body, tail];
}

/**
 * A line that is just a (keyword=) plain string literal, e.g. an argument on its own line: split it at spaces into
 * adjacent literals, which Python concatenates. Anything else is returned unchanged.
 */
function splitString(line: string, max: number): string[] {
  const m = /^( *)((?:[A-Za-z_]\w*=)?)"((?:[^"\\]|\\.)*)"$/.exec(line);
  if (!m) return [line];
  const [, indent, kw, body] = m as unknown as [string, string, string, string];
  const width = max - indent.length - kw.length - 2;
  const words = body.split(" ");
  const chunks: string[] = [];
  let cur = "";
  for (const w of words) {
    if (cur && cur.length + 1 + w.length > width) {
      chunks.push(`${cur} `);
      cur = w;
    } else {
      cur = cur ? `${cur} ${w}` : w;
    }
  }
  chunks.push(cur);
  if (chunks.length < 2) return [line];
  return chunks.map((c, i) => `${indent}${i === 0 ? kw : " ".repeat(kw.length)}"${c}"`);
}

function splitTopLevel(s: string): string[] {
  const out: string[] = [];
  let start = 0;
  for (const i of topLevel(s, ",")) {
    out.push(s.slice(start, i));
    start = i + 1;
  }
  const last = s.slice(start);
  if (last.trim()) out.push(last);
  return out;
}
